"""manifest.yml renderer.

We render YAML by hand (rather than via PyYAML's `yaml.dump`) because we need
explicit control over key ordering AND a "Probably change this" comment placed
immediately above the `database:` line. PyYAML cannot interleave comments.
For each templating-default value we still delegate to `yaml.safe_dump` to get
correct YAML for arbitrary structures (mappings, lists, numbers, bools, null).
"""

from __future__ import annotations

from datetime import date
from io import StringIO
from typing import Any

import yaml

from dcmassist.config import Config


_HEADER = (
    f"# Generated by dcmassist on {date.today().isoformat()}.\n"
    "# Review the project_owner field below — it is left blank intentionally.\n"
)


def _yaml_scalar(value: Any) -> str:
    """Dump a single value to YAML, returning the trimmed result."""
    text = yaml.safe_dump(value, default_flow_style=False, sort_keys=False).rstrip()
    return text


def _emit_value_inline(buf: StringIO, indent: str, key: str, value: Any) -> None:
    """Emit `<indent><key>: <value>` for scalars, or a nested block for collections."""
    if isinstance(value, (dict, list)):
        rendered = yaml.safe_dump(
            {key: value}, default_flow_style=False, sort_keys=False
        ).rstrip()
        for line in rendered.splitlines():
            buf.write(f"{indent}{line}\n")
        return

    if isinstance(value, str):
        # Quote empty strings and strings that look like YAML keywords.
        if value == "":
            buf.write(f'{indent}{key}: ""\n')
            return
    buf.write(f"{indent}{key}: {_yaml_scalar(value)}\n")


def render_manifest(cfg: Config, *, account_identifier: str) -> str:
    """Render manifest.yml for a Config + resolved account identifier."""
    buf = StringIO()
    buf.write("manifest_version: 2\n")
    buf.write("type: DCM_PROJECT\n")
    buf.write("\n")
    buf.write(_HEADER)
    buf.write("\n")

    buf.write("targets:\n")
    for target in cfg.targets:
        buf.write(f"  {target}:\n")
        if account_identifier:
            buf.write(f"    account_identifier: {account_identifier}\n")
        else:
            buf.write('    account_identifier: ""\n')
        buf.write(f"    project_name: {cfg.database}.PUBLIC.MAIN\n")
        buf.write('    project_owner: ""\n')
        if cfg.configurations:
            buf.write(f"    templating_config: {target}\n")

    buf.write("\n")
    buf.write("templating:\n")
    buf.write("  defaults:\n")

    if not cfg.configurations:
        buf.write(
            "    # Probably change this — generated from the exported-from database\n"
        )
        buf.write(f"    database: {cfg.database}\n")

    for key, value in cfg.templating_defaults:
        _emit_value_inline(buf, "    ", key, value)

    if cfg.configurations:
        buf.write("  configurations:\n")
        for name in cfg.configurations:
            buf.write(f"    {name}:\n")
            buf.write(
                "      # Probably change this — "
                "generated from the exported-from database\n"
            )
            buf.write(f"      database: {cfg.database}\n")
            for key in cfg.templating_configuration_keys:
                buf.write(f'      {key}: ""\n')

    return buf.getvalue()
